/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    events: Event;
    blogs: Blog;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    events: EventsSelect<false> | EventsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'ipdcp-page': IpdcpPage;
    settings: Setting;
  };
  globalsSelect: {
    'ipdcp-page': IpdcpPageSelect<false> | IpdcpPageSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * One row per event. Set Featured = true on exactly one event — it appears at the top of the Events page. Upcoming/Past status drives which list it shows up in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * Shown on cards and the detail page hero.
   */
  title: string;
  type:
    | 'Webinar'
    | 'Workshop'
    | 'Conference'
    | 'Community Meetup'
    | 'Summit'
    | 'Competition'
    | 'Industry Visit'
    | 'Event';
  /**
   * Upcoming / Featured / Past — drives which list this appears in.
   */
  tag: 'Upcoming' | 'Featured' | 'Past';
  /**
   * Set this for exactly ONE event — it becomes the hero.
   */
  featured?: boolean | null;
  /**
   * Optional. Lower numbers show first. Leave blank to sort by date.
   */
  displayOrder?: number | null;
  /**
   * Human-readable date string.
   */
  date: string;
  time: string;
  location: string;
  /**
   * Longer label for the detail page.
   */
  format?: string | null;
  /**
   * Optional machine-readable date — used for sorting and calendar features.
   */
  isoDate?: string | null;
  /**
   * 1–2 lines shown on event cards.
   */
  summary: string;
  /**
   * Longer paragraph shown on the detail page 'About This Event' section.
   */
  fullDescription?: string | null;
  /**
   * Tags shown as pills on the detail page.
   */
  topics?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Eligibility / requirements callout. Leave blank if none.
   */
  prerequisites?: string | null;
  /**
   * Total seats. Upcoming events only.
   */
  capacity?: number | null;
  /**
   * Registered count. Drives the capacity bar.
   */
  registered?: number | null;
  /**
   * Schedule for the event. One row per session/break.
   */
  agenda?:
    | {
        time: string;
        title: string;
        speaker?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Featured speakers shown in the 'Who You'll Hear From' section.
   */
  speakers?:
    | {
        name: string;
        role: string;
        /**
         * Optional. If blank, the speaker's initials are shown in a gradient circle.
         */
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * PAST events only. Label of the action link on past-event cards.
   */
  pastAction?: ('View Highlights' | 'Watch Recording' | 'Read Recap') | null;
  /**
   * PAST events only. Key takeaways shown with checkmarks.
   */
  highlights?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  recordingUrl?: string | null;
  recapUrl?: string | null;
  /**
   * Event photos. First photo is used as the hero banner on the detail page. Drag to reorder.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal notes (sponsors, livestream URLs, etc.). NOT shown on the public site.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * All event photos, speaker photos, and any other uploads. Files are stored on disk in backend/media/. Make sure to back up this folder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility. Describe what's in the photo.
   */
  alt?: string | null;
  /**
   * Optional caption shown under the photo in galleries.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    avatar?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Long-form blog content. Set Status = Published to make a post visible on the public site. Draft posts stay hidden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  category: 'Insight' | 'Tutorial' | 'Announcement' | 'Case Study' | 'Interview' | 'Research' | 'Industry';
  /**
   * URL-friendly identifier. Leave blank to auto-derive from the title.
   */
  slug?: string | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Set on ONE post — it becomes the hero on the blog index.
   */
  featured?: boolean | null;
  author: string;
  authorRole?: string | null;
  /**
   * Optional. If blank, the author's initials are shown in a circle.
   */
  authorPhoto?: (number | null) | Media;
  /**
   * Used for sorting. Date shown on the public site.
   */
  publishedDate: string;
  /**
   * Auto-estimated from body length on save. Override if you want.
   */
  readingTimeMinutes?: number | null;
  /**
   * 1–2 lines shown on blog cards and used as a meta description.
   */
  excerpt: string;
  /**
   * Featured image used as the card thumbnail and detail-page banner.
   */
  coverImage?: (number | null) | Media;
  /**
   * The article itself. Headings, paragraphs, lists, images inline, quotes, links.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Free-text tags shown as pills on the detail page.
   */
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional photo gallery on the detail page, after the body.
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. Other posts shown at the bottom of this post's detail page.
   */
  relatedPosts?: (number | Blog)[] | null;
  /**
   * Editor-only notes. Not shown publicly.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can log in to the CMS. Create the first user when you visit /admin for the first time.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name shown in the admin UI.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  tag?: T;
  featured?: T;
  displayOrder?: T;
  date?: T;
  time?: T;
  location?: T;
  format?: T;
  isoDate?: T;
  summary?: T;
  fullDescription?: T;
  topics?:
    | T
    | {
        value?: T;
        id?: T;
      };
  prerequisites?: T;
  capacity?: T;
  registered?: T;
  agenda?:
    | T
    | {
        time?: T;
        title?: T;
        speaker?: T;
        id?: T;
      };
  speakers?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  pastAction?: T;
  highlights?:
    | T
    | {
        value?: T;
        id?: T;
      };
  recordingUrl?: T;
  recapUrl?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  slug?: T;
  status?: T;
  featured?: T;
  author?: T;
  authorRole?: T;
  authorPhoto?: T;
  publishedDate?: T;
  readingTimeMinutes?: T;
  excerpt?: T;
  coverImage?: T;
  body?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  relatedPosts?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        avatar?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Content for all 8 slides of the iPD-CP scroll story on the homepage. Visual styling and animations stay in code — only text, numbers, and lists are edited here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ipdcp-page".
 */
export interface IpdcpPage {
  id: number;
  /**
   * Opening intro card with stats.
   */
  slide01?: {
    headline?: string | null;
    body?: string | null;
    goalLabel?: string | null;
    goalText?: string | null;
    /**
     * The 3 number+label stats shown under the goal card.
     */
    stats?:
      | {
          number: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  slide02?: {
    headline?: string | null;
    body?: string | null;
    /**
     * Feature list shown to the right of the PCB animation.
     */
    features?:
      | {
          /**
           * A single symbol or emoji (◈ ⬡ ◎).
           */
          icon: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  slide03?: {
    headline?: string | null;
    body?: string | null;
    modules?:
      | {
          /**
           * Symbol/emoji (◐ ◑ ◒).
           */
          icon: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  slide04?: {
    headline?: string | null;
    body?: string | null;
    audiences?:
      | {
          /**
           * Emoji (🎓 ⚡ 🚀 ⚙️).
           */
          icon: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  slide05?: {
    headline?: string | null;
    body?: string | null;
    /**
     * Video testimonials. Upload .mp4 files and poster image.
     */
    testimonials?:
      | {
          name: string;
          batch: string;
          /**
           * Video file (.mp4 preferred). Upload to Media library first or here.
           */
          video?: (number | null) | Media;
          /**
           * Thumbnail image shown before the video plays.
           */
          poster?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  slide06?: {
    headline?: string | null;
    body?: string | null;
    onboarding?: {
      title?: string | null;
      subtitle?: string | null;
      /**
       * Each GPA tier card.
       */
      tiers?:
        | {
            criterion: string;
            feeAfter: string;
            scholarshipAmount: string;
            /**
             * Accent color for this card.
             */
            color?: ('teal' | 'magenta' | 'gold') | null;
            id?: string | null;
          }[]
        | null;
    };
    fellowship?: {
      title?: string | null;
      subtitle?: string | null;
      stats?:
        | {
            label: string;
            value: string;
            note: string;
            id?: string | null;
          }[]
        | null;
      eligibilityNote?: string | null;
    };
  };
  slide07?: {
    headline?: string | null;
    body?: string | null;
    sectionTitle?: string | null;
    sectionSubtitle?: string | null;
    grants?:
      | {
          name: string;
          amount: string;
          description: string;
          color?: ('gold' | 'teal' | 'magenta') | null;
          id?: string | null;
        }[]
      | null;
  };
  slide08: {
    headline?: string | null;
    cohortLabel?: string | null;
    cohortDate?: string | null;
    limitedSeatsLabel?: string | null;
    /**
     * Use **bold** for the deadline sentence on the public site.
     */
    deadlineNote?: string | null;
    /**
     * URL the 'Apply Now' button opens.
     */
    applyUrl: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site-wide values: Apply Now URL, application deadline, navbar links, hero copy. Edits here apply everywhere on the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Where the 'Apply Now' button takes users (navbar + floating CTA + iPD-CP CTA).
   */
  applyUrl: string;
  /**
   * Drives the countdown in the floating CTA bar.
   */
  applicationDeadline: string;
  /**
   * Eyebrow text above the date in the CTA.
   */
  deadlineLabel?: string | null;
  /**
   * Optional tagline that appears over the hero video.
   */
  heroTagline?: string | null;
  /**
   * Optional secondary line under the tagline.
   */
  heroSubcopy?: string | null;
  /**
   * Links shown in the top navigation. 'phase' must match an internal section name.
   */
  navLinks?:
    | {
        label: string;
        phase: 'hero' | 'story' | 'ipdcp' | 'events';
        id?: string | null;
      }[]
    | null;
  /**
   * Label of the navbar CTA button.
   */
  ctaLabel?: string | null;
  /**
   * Brand text shown on the left of the floating bar.
   */
  fctaBrand?: string | null;
  /**
   * Tagline shown under the brand.
   */
  fctaSubtext?: string | null;
  fctaButtonLabel?: string | null;
  /**
   * Public contact email (e.g., for event inquiries).
   */
  contactEmail?: string | null;
  /**
   * Optional contact phone.
   */
  contactPhone?: string | null;
  address?: string | null;
  /**
   * Optional social media links.
   */
  socialLinks?:
    | {
        platform: 'linkedin' | 'twitter' | 'instagram' | 'youtube' | 'github';
        url: string;
        id?: string | null;
      }[]
    | null;
  blogsKicker?: string | null;
  blogsHeadline?: string | null;
  blogsLead?: string | null;
  blogsBody?: string | null;
  eventsKicker?: string | null;
  eventsHeadline?: string | null;
  eventsLead?: string | null;
  eventsBody?: string | null;
  subscribeBody?: string | null;
  /**
   * Quote cards shown in the 'What attendees say' section on the Events page.
   */
  eventTestimonials?:
    | {
        quote: string;
        /**
         * Attribution line — e.g., 'Senior HRBP, Tech Firm'.
         */
        by: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ipdcp-page_select".
 */
export interface IpdcpPageSelect<T extends boolean = true> {
  slide01?:
    | T
    | {
        headline?: T;
        body?: T;
        goalLabel?: T;
        goalText?: T;
        stats?:
          | T
          | {
              number?: T;
              label?: T;
              id?: T;
            };
      };
  slide02?:
    | T
    | {
        headline?: T;
        body?: T;
        features?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  slide03?:
    | T
    | {
        headline?: T;
        body?: T;
        modules?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  slide04?:
    | T
    | {
        headline?: T;
        body?: T;
        audiences?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  slide05?:
    | T
    | {
        headline?: T;
        body?: T;
        testimonials?:
          | T
          | {
              name?: T;
              batch?: T;
              video?: T;
              poster?: T;
              id?: T;
            };
      };
  slide06?:
    | T
    | {
        headline?: T;
        body?: T;
        onboarding?:
          | T
          | {
              title?: T;
              subtitle?: T;
              tiers?:
                | T
                | {
                    criterion?: T;
                    feeAfter?: T;
                    scholarshipAmount?: T;
                    color?: T;
                    id?: T;
                  };
            };
        fellowship?:
          | T
          | {
              title?: T;
              subtitle?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    note?: T;
                    id?: T;
                  };
              eligibilityNote?: T;
            };
      };
  slide07?:
    | T
    | {
        headline?: T;
        body?: T;
        sectionTitle?: T;
        sectionSubtitle?: T;
        grants?:
          | T
          | {
              name?: T;
              amount?: T;
              description?: T;
              color?: T;
              id?: T;
            };
      };
  slide08?:
    | T
    | {
        headline?: T;
        cohortLabel?: T;
        cohortDate?: T;
        limitedSeatsLabel?: T;
        deadlineNote?: T;
        applyUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  applyUrl?: T;
  applicationDeadline?: T;
  deadlineLabel?: T;
  heroTagline?: T;
  heroSubcopy?: T;
  navLinks?:
    | T
    | {
        label?: T;
        phase?: T;
        id?: T;
      };
  ctaLabel?: T;
  fctaBrand?: T;
  fctaSubtext?: T;
  fctaButtonLabel?: T;
  contactEmail?: T;
  contactPhone?: T;
  address?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  blogsKicker?: T;
  blogsHeadline?: T;
  blogsLead?: T;
  blogsBody?: T;
  eventsKicker?: T;
  eventsHeadline?: T;
  eventsLead?: T;
  eventsBody?: T;
  subscribeBody?: T;
  eventTestimonials?:
    | T
    | {
        quote?: T;
        by?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}